[v1]
"bat 0.22.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["bat"]
"coreutils 0.0.17 (registry+https://github.com/rust-lang/crates.io-index)" = ["coreutils"]
"du-dust 0.8.5 (registry+https://github.com/rust-lang/crates.io-index)" = ["dust"]
"evcxr_jupyter 0.14.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["evcxr_jupyter"]
"exa 0.10.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["exa"]
"fd-find 8.7.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["fd"]
"fzf 0.1.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["fzf"]
"gitui 0.22.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["gitui"]
"jless 0.8.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["jless"]
"mprocs 0.6.4 (registry+https://github.com/rust-lang/crates.io-index)" = ["mprocs"]
"porsmo 0.1.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["porsmo"]
"ripgrep 13.0.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["rg"]
"taplo-cli 0.8.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["taplo"]
"zoxide 0.9.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["zoxide"]
