---
- ansible.builtin.homebrew:
    state: present

- community.general.homebrew:
    update_homebrew: true
    upgrade_all: true

- name: Install packages from Brewfile
  command: brew bundle --file=../../homebrew/Brewfile
  register: brew_output

- debug:
    var: brew_output.stdout_lines

- name: Run brew cleanup
  shell: brew cleanup
  register: brew_cleanup

- debug:
    var: brew_cleanup.stdout_lines

- name: Set macOS screencapture location to ~/Downloads
  shell: defaults write com.apple.screencapture location ~/Downloads 
  when: ansible_facts['os_family'] == "Darwin"
