---
- name: Check if Homebrew is installed and install if missing
  shell: "{{ item }}"
  loop:
    - which brew || /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    - eval "$(/opt/homebrew/bin/brew shellenv)"
  register: brew_exists
  ignore_errors: true

- name: Install or upgrade Homebrew packages
  shell: |
    brew update
    brew install ack curl fish git nmap node python readline ssh-copy-id vim wget zsh httpie tree openssl coreutils findutils mosh htop tmux
  when: brew_exists.results[-1].rc == 0

- name: Run brew cleanup
  shell: brew cleanup
  when: brew_exists.results[-1].rc == 0

- name: Set macOS screencapture location to ~/Downloads
  shell: defaults write com.apple.screencapture location ~/Downloads && killall SystemUIServer
  when: ansible_facts['os_family'] == "Darwin"
