name: Ansible MacOS

on:
  push:
    branches:
      - staging

defaults:
  run:
    working-directory: ansible/playbooks

jobs:
  ansible-build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ansible
        run: |
          brew install ansible

      - name: Pre-Installation Verification
        run: |
          cat ./library/* 2>/dev/null || true
          cat ./* 2>/dev/null || true

      - name: Install stow
        run: |
          brew tap homebrew/core
          brew extract --version=2.4.0 stow homebrew/cask-versions
          brew install homebrew/cask-versions/stow@2.4.0

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -c local -i inventory osx.yaml

      - name: Pre-Installation Verification
        run: |
          cat ~/.zshrc
          cat ~/.config/helix/*
          ls ~/.config

