# .github/workflows/release.yaml
name: MacOS Build setup_quanianitis

on:
  push:
    branches:
      - staging
      - main

jobs:
  setup-quanianitis:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install stow
        run: brew install stow

      - name: Build Go
        run: GOOS=darwin go build -o setup_quanianitis

      - name: Test Go
        run: go test -v ./...

      - name: Run setup_quanianitis
        run: ./setup_quanianitis
        continue-on-error: true
        env:
          ENABLE_CICD: "true"
          ACTIONS_WORKSPACE: ${{ github.workspace }}

      - name: Post-Installation Verification
        run: |
          cat ${{ github.workspace }}/.config/alacritty/* || true
          cat ${{ github.workspace }}/.config/helix/* || true
          cat ${{ github.workspace }}/.zshrc || true
          ls ${{ github.workspace }}/.config || true

      - name: Pre-Installation Verification
        run: |
          cat ~/.zshrc
          cat ~/.config/helix/*
          ls ~/.config

