name: Ansible MacOS

on:
  push:
    branches:
      - staging

jobs:
  setup-quanianitis:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install stow
        run: brew install stow

      - name: Build Go
        run: GOOS=darwin go build -o /Users/runner/setup_quanianitis

      - name: Test Go
        run: go test -v ./...

      - name: Run setup_quanianitis
        run: ./setup_quanianitis
        working-directory: /Users/runner

      - name: Pre-Installation Verification
        run: |
          cat ~/.zshrc
          cat ~/.config/helix/*
          ls ~/.config

