name: Ansible MacOS

on:
  push:
    branches:
      - staging

defaults:
  run:
    working-directory: ansible/playbooks

jobs:
  ansible-build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ansible
        run: |
          brew install ansible

      - name: Download Stow Module for Ansible
        run: |
          wget https://raw.githubusercontent.com/caian-org/ansible-stow/v1.2.1/stow
          mkdir -p ./library
          mv stow ./library/

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -c local -i inventory osx.yaml

